ALTER TABLE mydb.Users ADD COLUMN review VARCHAR(255) NOT NULL AFTER phone;
ALTER TABLE mydb.Car_brands MODIFY COLUMN name VARCHAR(255) NOT NULL;
ALTER TABLE mydb.Cars ADD COLUMN color VARCHAR(45) NOT NULL AFTER user_id;
ALTER TABLE mydb.Service_stations MODIFY COLUMN address VARCHAR(255) NOT NULL;
ALTER TABLE mydb.Car_parts ADD COLUMN quantity INT NOT NULL DEFAULT 0 AFTER serial_number;