-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 14:19:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- This small business model utilizes the MySQL database provided in the script to manage a car service company. 
-- The database includes tables for "Users", "Car_brands", "Brand_models", and "Cars", which represent customers, car brands, car models, 
-- and the cars themselves respectively. The "Users" table stores customer information such as their name, id number and phone number. 
-- The "Car_brands" and "Brand_models" tables store information about the different car brands and models available.
--  The "Cars" table stores information about the cars, including the year and the customer and car brand and model. 
--  This database can be used to track customer information, car inventory, and service history. 
--  Additionally, it has foreign key constraints that ensure referential integrity and cascading actions when related records are deleted or updated.
-- In addition to the tables described above, this MySQL database also include tables for "Service_Orders" and "Shop_Orders" to manage service and shop orders respectively.
-- The "Service_Orders" table store information about service orders such as the customer's name, the car being serviced, the service being performed,
--  and the date of the service. It also have foreign key constraints linking it to the "Users" and "Cars" tables.
-- The "Shop_Orders" table store information about shop orders such as the customer's name, the car parts being purchased, the quantity of each part, 
-- and the date of the order. It also have foreign key constraints linking it to the "Users" table.
-- These additional tables allow the company to keep track of service and shop orders and retrieve the relevant information in a structured way. 
-- This will help in providing better services to customers and keeping track of inventory and parts.
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `id_number` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Car_brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Brand_Models_Car_brands1_idx` (`Car_brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Models_Car_brands1`
    FOREIGN KEY (`Car_brands_id`)
    REFERENCES `mydb`.`Car_brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `Car_brands_id` INT NOT NULL,
  `Brand_Models_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Cars_Car_brands1_idx` (`Car_brands_id` ASC) VISIBLE,
  INDEX `fk_Cars_Brand_Models1_idx` (`Brand_Models_id` ASC) VISIBLE,
  CONSTRAINT `fk_cars_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Car_brands1`
    FOREIGN KEY (`Car_brands_id`)
    REFERENCES `mydb`.`Car_brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Brand_Models1`
    FOREIGN KEY (`Brand_Models_id`)
    REFERENCES `mydb`.`Brand_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_part_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_part_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `serial_number` VARCHAR(45) NOT NULL,
  `price` DECIMAL(9) NOT NULL,
  `Car_part_categories_id` INT NOT NULL,
  `Shops_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Car_Parts_Car_part_categories1_idx` (`Car_part_categories_id` ASC) VISIBLE,
  INDEX `fk_Car_Parts_Shops1_idx` (`Shops_id` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Parts_Car_part_categories1`
    FOREIGN KEY (`Car_part_categories_id`)
    REFERENCES `mydb`.`Car_part_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_Parts_Shops1`
    FOREIGN KEY (`Shops_id`)
    REFERENCES `mydb`.`Shops` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  `Shops_id` INT NOT NULL,
  `Car_Parts_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `Users_id`, `Shops_id`),
  INDEX `fk_Users_has_Shops_Shops1_idx` (`Shops_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Shops_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Shop_Orders_Car_Parts1_idx` (`Car_Parts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Shops_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Shops_Shops1`
    FOREIGN KEY (`Shops_id`)
    REFERENCES `mydb`.`Shops` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shop_Orders_Car_Parts1`
    FOREIGN KEY (`Car_Parts_id`)
    REFERENCES `mydb`.`Car_parts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Service_Stations_id` INT NOT NULL,
  `Cars_id` INT NOT NULL,
  `Car_Services_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Service_Stations_id`, `Cars_id`),
  INDEX `fk_Service_Stations_has_Cars_Cars1_idx` (`Cars_id` ASC) VISIBLE,
  INDEX `fk_Service_Stations_has_Cars_Service_Stations1_idx` (`Service_Stations_id` ASC) VISIBLE,
  INDEX `fk_Service_Orders_Car_Services1_idx` (`Car_Services_id` ASC) VISIBLE,
  INDEX `fk_Service_orders_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Service_Stations_has_Cars_Service_Stations1`
    FOREIGN KEY (`Service_Stations_id`)
    REFERENCES `mydb`.`Service_stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Stations_has_Cars_Cars1`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Orders_Car_Services1`
    FOREIGN KEY (`Car_Services_id`)
    REFERENCES `mydb`.`Car_services` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_orders_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models_parts_compatibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Models_parts_compatibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Brand_Models_id` INT NOT NULL,
  `Car_Parts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Brand_Models_id`, `Car_Parts_id`),
  INDEX `fk_Brand_Models_has_Car_Parts_Car_Parts1_idx` (`Car_Parts_id` ASC) VISIBLE,
  INDEX `fk_Brand_Models_has_Car_Parts_Brand_Models1_idx` (`Brand_Models_id` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Models_has_Car_Parts_Brand_Models1`
    FOREIGN KEY (`Brand_Models_id`)
    REFERENCES `mydb`.`Brand_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brand_Models_has_Car_Parts_Car_Parts1`
    FOREIGN KEY (`Car_Parts_id`)
    REFERENCES `mydb`.`Car_parts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
